security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt
  providers:
    db_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      pattern: ^/
      provider: db_provider
      user_checker: App\Security\UserChecker
      form_login:
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager
      logout:
        path:   /logout
        target: /

  access_control:
    - { path: ^/$|^/login$|^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY}
